[profile.default]
  evm_version = "paris"
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 30
  out = "out"
  solc_version = "0.8.23"
  src = "src"
  via_ir = false

[fmt]
  line_length = 100
  multiline_func_header = "params_first"
  # wrap_comments = true

[profile.production]
  via_ir = true

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
